{% set name = 'bob.devtools' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - bdt = bob.devtools.scripts.bdt:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ environ.get('RECIPE_DIR') + '/..' }}
    {% if environ.get('BUILD_EGG') and not os.path.exists('dist') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python
    - setuptools
    - black >=19
    - click >=7
    - click-plugins
    # conda, conda-build, mamba, boa versions below are the same versions as in
    # bob.devtools/bob/devtools/bootstrap.py
    - conda=22
    - conda-build=3
    - mamba=1
    - boa=0.14
    - certifi
    - docformatter
    - git  # [linux]
    - pytz
    - python-dateutil
    - gitpython
    - python-gitlab
    - requests
    - sphinx >=4.0.2
    - pyyaml >=5.1
    - twine
    - lxml
    - jinja2
    - termcolor
    - psutil
    - tabulate
    - python-graphviz
    - pip
    - webdavclient3
    - pre-commit

test:
  requires:
    - sphinx_rtd_theme
    - pytest
    - pytest-cov
  imports:
    - {{ name }}
  commands:
    - bdt -h
    - bdt -?
    - bdt --help
    - bdt dumpsphinx --help
    - bdt dumpsphinx https://docs.python.org/3/objects.inv > /dev/null
    - bdt dev create --help
    - bdt build --help
    - bdt mirror --help
    - bdt rebuild --help
    - bdt test --help
    - bdt caupdate --help
    - bdt dev new --help
    - bdt dev new -t "New package" -o bob.foobar bob/bob.foobar "John Doe" "joe.doe@example.com"
    - bdt dev new -t "New package" -l bsd -o bob.foobar2 bob/bob.foobar "John Doe" "joe.doe@example.com"
    - bdt dev new -t "New package" -l bsd -o beat.foobar beat/beat.foobar "John Doe" "joe.doe@example.com"
    - bdt gitlab --help
    - bdt gitlab lasttag --help
      #- bdt gitlab lasttag -vv bob/bob.devtools
    - bdt gitlab commitfile --help
    - bdt gitlab changelog --help
      #- bdt gitlab changelog -vv bob/bob.devtools changelog.md
    - bdt gitlab release --help
      #- bdt gitlab release -vvd changelog.md
    - bdt gitlab visibility --help
      #- bdt gitlab visibility -vv bob/bob.devtools
    - bdt gitlab getpath --help
      #- bdt gitlab getpath -vv bob/bob.devtools .gitignore
    - bdt gitlab runners --help
    - bdt gitlab jobs --help
    - bdt ci --help
    - bdt ci base-build --help
    - bdt ci build --help
    - bdt ci base-deploy --help
    - bdt ci deploy --help
    - bdt ci pypi --help
    - bdt ci readme --help
    - bdt ci clean --help
    - bdt ci nightlies --help
    - bdt ci docs --help
    - bdt ci clean-betas --help
    - bdt ci check --help
    - bdt dav --help
    - bdt dav list --help
    - bdt dav makedirs --help
    - bdt dav rmtree --help
    - bdt dav clean-betas --help
    - bdt dav upload --help
    - bdt gitlab process-pipelines --help
    - bdt gitlab get-pipelines --help
    - bdt gitlab graph --help
    - bdt gitlab badges --help
    - bdt sphinx --help
    - bdt sphinx migrate-autodoc-flags --help
    - bdt gitlab alt-nightlies --help
    - pytest --capture=no --verbose --cov {{ name }} --cov-report term-missing --cov-report html:sphinx/coverage --cov-report xml:coverage.xml --pyargs {{ name }}
    - sphinx-build -aEW ${PREFIX}/share/doc/{{ name }}/doc sphinx
    {% if not os.path.exists('sphinx') %}
    - if [ -n "${CI_PROJECT_DIR}" ]; then mv sphinx "${CI_PROJECT_DIR}/"; fi
    {% endif %}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Tools for development and CI integration of Bob packages
  license_family: BSD
